# Ski Recommender CircleCI configuration file

version: 2
jobs:
  build:
    parallelism: 1
    machine:
      docker_layer_caching: true
    working_directory: ~/ski-recommender

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            docker build -t ski-recommender:development .

      - run:
          name: Run Tests
          command: |
            docker run ski-recommender:development pytest tests/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
