# Ski Recommender CircleCI configuration file

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-stretch
    parallelism: 1
    working_directory: ~/ski-recommender

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t ski-recommender:development .

      - run:
          name: Run Tests
          command: |
            docker run ski-recommender:development pytest tests/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
